### ISSUE TITLE
Example.html will not load if there is a space in the path to the directory

### ISSUE THREAD

**Issue by JaredMonkey** [webaverse/metachromium-bin#2]
Going through the steps to get started. If there is a space in the path that the browser is extracted to, example.html doesn't load.

**Comment by avaer** [comment]
Probably need to feed %20's in `metachromium.cmd` when it's passed in.

**Comment by avaer** [comment]
https://github.com/webaverse/metachromium/blob/hack/metachromium.cmd#L1

**Comment by avaer** [comment]
> wrapping in quotes fixes: "%cd%/example.html"

**Comment by avaer** [comment]
Fixed with https://github.com/webaverse/metachromium/commit/6d646a9c1845cf659817c2f2f270453b8e402fe3
