### ISSUE TITLE
I am moved around in SteamVR when I start an XR session sometimes.

### ISSUE THREAD

**Issue by JaredMonkey** [webaverse/metachromium-bin#9]
This appears to only happen when the SteamVR tracking configuration is different than the primary app. If I am I a seated app I am moved when I establish a WebXR session.

**Comment by avaer** [comment]
Only when seated? Is this Scene App-specific?

**Comment by avaer** [comment]
This might be fixed now, since we no longer set standing/sitting compositor mode on starting a session.

@JaredMonkey Could you test again?

**Comment by avaer** [comment]
Closing due to no follow-up.
